language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install: 
  - "python setup.py -q install"
  - "pip install pytest-pep8 pytest-cov codecov"
# command to run tests
script:
  - "pytest --cov=./"
after_success:
  - codecov
